// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: appointments.sql

package db

import (
	"context"
)

const createAppointment = `-- name: CreateAppointment :exec
INSERT INTO appointments (booking_id, schedule_id, customer_id)
VALUES ($1, $2, $3)
`

type CreateAppointmentParams struct {
	BookingID  int64 `json:"booking_id"`
	ScheduleID int64 `json:"schedule_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, createAppointment, arg.BookingID, arg.ScheduleID, arg.CustomerID)
	return err
}
