// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: bookings.sql

package db

import (
	"context"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (customer_id, customer_note, payment_id)
VALUES ($1, $2, $3) RETURNING id, customer_id, customer_note, payment_status, payment_id, is_cancelled, created_at
`

type CreateBookingParams struct {
	CustomerID   int64  `json:"customer_id"`
	CustomerNote string `json:"customer_note"`
	PaymentID    int64  `json:"payment_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking, arg.CustomerID, arg.CustomerNote, arg.PaymentID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CustomerNote,
		&i.PaymentStatus,
		&i.PaymentID,
		&i.IsCancelled,
		&i.CreatedAt,
	)
	return i, err
}
