// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payments.sql

package db

import (
	"context"
)

const listAllPaymentMethods = `-- name: ListAllPaymentMethods :many
SELECT id, name, created_at
FROM payments
`

func (q *Queries) ListAllPaymentMethods(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listAllPaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
