// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) error
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAllServiceCategories(ctx context.Context) ([]ServiceCategory, error)
	ListAllServicesOfACategory(ctx context.Context, categoryID int64) ([]Service, error)
	ListExaminationAppointments(ctx context.Context, arg ListExaminationAppointmentsParams) ([]ListExaminationAppointmentsRow, error)
	ListExaminationSchedulesByDateAndServiceCategory(ctx context.Context, arg ListExaminationSchedulesByDateAndServiceCategoryParams) ([]ListExaminationSchedulesByDateAndServiceCategoryRow, error)
}

var _ Querier = (*Queries)(nil)
