// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (User, error)
	GetCustomerByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
