// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: schedules.sql

package db

import (
	"context"
	"database/sql"
)

const updateExaminationSchedule = `-- name: UpdateExaminationSchedule :exec
UPDATE examination_schedules SET booking_id = $2 AND customer_id = $3 WHERE id = $1
`

type UpdateExaminationScheduleParams struct {
	ID         int64         `json:"id"`
	BookingID  sql.NullInt64 `json:"booking_id"`
	CustomerID sql.NullInt64 `json:"customer_id"`
}

func (q *Queries) UpdateExaminationSchedule(ctx context.Context, arg UpdateExaminationScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateExaminationSchedule, arg.ID, arg.BookingID, arg.CustomerID)
	return err
}
