// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: service_categories.sql

package db

import (
	"context"
)

const listAllServiceCategories = `-- name: ListAllServiceCategories :many
SELECT id, name, image_url, slug, price, created_at FROM service_categories
`

func (q *Queries) ListAllServiceCategories(ctx context.Context) ([]ServiceCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAllServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCategory{}
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Slug,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
