// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: service_categories.sql

package db

import (
	"context"
)

const listAllServiceCategories = `-- name: ListAllServiceCategories :many
SELECT id, name, short_description, image_url, slug, price, created_at FROM service_categories
`

func (q *Queries) ListAllServiceCategories(ctx context.Context) ([]ServiceCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAllServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCategory{}
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortDescription,
			&i.ImageUrl,
			&i.Slug,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServicesOfACategory = `-- name: ListAllServicesOfACategory :many
SELECT id, name, category_id, unit, price, warranty_duration, created_at FROM services WHERE category_id = $1
`

func (q *Queries) ListAllServicesOfACategory(ctx context.Context, categoryID int64) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listAllServicesOfACategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Unit,
			&i.Price,
			&i.WarrantyDuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
