// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: services.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, category_id, unit, cost, warranty_duration)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, category_id, unit, cost, warranty_duration, created_at
`

type CreateServiceParams struct {
	Name             string `json:"name"`
	CategoryID       int64  `json:"category_id"`
	Unit             string `json:"unit"`
	Cost             int64  `json:"cost"`
	WarrantyDuration string `json:"warranty_duration"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Name,
		arg.CategoryID,
		arg.Unit,
		arg.Cost,
		arg.WarrantyDuration,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Cost,
		&i.WarrantyDuration,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, name, category_id, unit, cost, warranty_duration, created_at
FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Cost,
		&i.WarrantyDuration,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, category_id, unit, cost, warranty_duration, created_at
FROM services
ORDER BY id
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Unit,
			&i.Cost,
			&i.WarrantyDuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByName = `-- name: ListServicesByName :many
SELECT id, name, category_id, unit, cost, warranty_duration, created_at
FROM services
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY id
`

func (q *Queries) ListServicesByName(ctx context.Context, name string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Unit,
			&i.Cost,
			&i.WarrantyDuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET name              = $2,
    category_id       = $3,
    unit              = $4,
    cost              = $5,
    warranty_duration = $6
WHERE id = $1
`

type UpdateServiceParams struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	CategoryID       int64  `json:"category_id"`
	Unit             string `json:"unit"`
	Cost             int64  `json:"cost"`
	WarrantyDuration string `json:"warranty_duration"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Unit,
		arg.Cost,
		arg.WarrantyDuration,
	)
	return err
}
