// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: services.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, category_id, unit, cost, warranty_duration)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, category_id, unit, cost, warranty_duration, created_at
`

type CreateServiceParams struct {
	Name             string `json:"name"`
	CategoryID       int64  `json:"category_id"`
	Unit             string `json:"unit"`
	Cost             int64  `json:"cost"`
	WarrantyDuration string `json:"warranty_duration"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Name,
		arg.CategoryID,
		arg.Unit,
		arg.Cost,
		arg.WarrantyDuration,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Unit,
		&i.Cost,
		&i.WarrantyDuration,
		&i.CreatedAt,
	)
	return i, err
}
