// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: specialties.sql

package db

import (
	"context"
)

const createSpecialty = `-- name: CreateSpecialty :one
INSERT INTO specialties (name)
VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateSpecialty(ctx context.Context, name string) (Specialty, error) {
	row := q.db.QueryRowContext(ctx, createSpecialty, name)
	var i Specialty
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSpecialty = `-- name: GetSpecialty :one
SELECT id, name, created_at
FROM specialties
WHERE id = $1
`

func (q *Queries) GetSpecialty(ctx context.Context, id int64) (Specialty, error) {
	row := q.db.QueryRowContext(ctx, getSpecialty, id)
	var i Specialty
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listSpecialties = `-- name: ListSpecialties :many
SELECT id, name, created_at
FROM specialties
`

func (q *Queries) ListSpecialties(ctx context.Context) ([]Specialty, error) {
	rows, err := q.db.QueryContext(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Specialty{}
	for rows.Next() {
		var i Specialty
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
